interface ColorPaletteSlideProps {
  backgroundImage: string;
  isActive: boolean;
  slideIndex: number;
  animationClass?: string;
  colorType: "primary" | "secondary";
}

/**
 * ColorPaletteSlide - Displays brand color palette (Primary or Secondary)
 *
 * FUTURE: This data will be generated by GPT after analyzing the brand logo
 * Currently using hardcoded sample colors for demonstration
 */
export default function ColorPaletteSlide({
  isActive,
  slideIndex,
  animationClass = "",
  colorType,
}: ColorPaletteSlideProps) {

  // Fetch GPT-generated colors from localStorage
  const getBrandbookContent = () => {
    try {
      const stored = localStorage.getItem('brandbookContent');
      if (stored) {
        const content = JSON.parse(stored);
        return content.colorPalette;
      }
    } catch (error) {
      console.error('Error reading brandbook content from localStorage:', error);
    }
    // Fallback to default colors
    return {
      primary: {
        name: "Primary Color",
        mainColor: "#8F00FF",
        shades: [
          { hex: "#E5CCFF", rgb: "229, 204, 255", cmyk: "10, 20, 0, 0" },
          { hex: "#B366FF", rgb: "179, 102, 255", cmyk: "30, 60, 0, 0" },
          { hex: "#8F00FF", rgb: "143, 0, 255", cmyk: "44, 100, 0, 0" },
          { hex: "#6600B3", rgb: "102, 0, 179", cmyk: "43, 100, 0, 30" },
        ],
      },
      secondary: {
        name: "Secondary Color",
        mainColor: "#DAABFF",
        shades: [
          { hex: "#F5EBFF", rgb: "245, 235, 255", cmyk: "4, 8, 0, 0" },
          { hex: "#DAABFF", rgb: "218, 171, 255", cmyk: "15, 33, 0, 0" },
          { hex: "#C285FF", rgb: "194, 133, 255", cmyk: "24, 48, 0, 0" },
          { hex: "#A855F7", rgb: "168, 85, 247", cmyk: "32, 66, 0, 3" },
        ],
      },
    };
  };

  const colorData = getBrandbookContent();
  const selectedColor = colorData[colorType];

  return (
    <div
      data-slide={slideIndex}
      className={`absolute inset-0 ${animationClass}`}
      style={{
        opacity: isActive || animationClass ? 1 : 0,
        pointerEvents: isActive ? "auto" : "none",
        zIndex: isActive ? 10 : animationClass ? 9 : 0,
        backgroundColor: "#FFFFFF",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        overflow: "auto",
      }}
    >
      {/* Main Container */}
      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          padding: "80px 120px",
          gap: "60px",
        }}
      >
        {/* Header */}
        <div style={{ textAlign: "center", flexShrink: 0 }}>
          <h1
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: "64px",
              fontWeight: 700,
              color: "#0A0A0A",
              marginBottom: "16px",
              letterSpacing: "-0.02em",
            }}
          >
            {colorType === "primary" ? "Primary Color" : "Secondary Color"}
          </h1>
          <p
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: "20px",
              color: "#6B7280",
              fontWeight: 400,
            }}
          >
            {selectedColor.name} ({selectedColor.mainColor})
          </p>
        </div>

        {/* Color Bars Grid */}
        <div
          style={{
            width: "100%",
            maxWidth: "1400px",
            flexShrink: 0,
          }}
        >
          {/* Color Bars Row */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(4, 1fr)",
              gap: "32px",
              marginBottom: "32px",
            }}
          >
            {selectedColor.shades.map((shade: any, idx: number) => (
              <div
                key={idx}
                style={{
                  width: "100%",
                  height: "350px",
                  backgroundColor: shade.hex,
                  borderRadius: "16px",
                  boxShadow: "0 8px 32px rgba(0, 0, 0, 0.12)",
                  transition: "transform 0.3s ease",
                }}
              />
            ))}
          </div>

          {/* Color Info Table */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "120px repeat(4, 1fr)",
              gap: "32px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            {/* Labels Column */}
            <div style={{ display: "flex", flexDirection: "column", gap: "16px", paddingTop: "8px" }}>
              <div style={{ fontSize: "16px", fontWeight: 600, color: "#1F2937", height: "32px", display: "flex", alignItems: "center" }}>HEX</div>
              <div style={{ fontSize: "16px", fontWeight: 600, color: "#1F2937", height: "32px", display: "flex", alignItems: "center" }}>RGB</div>
              <div style={{ fontSize: "16px", fontWeight: 600, color: "#1F2937", height: "32px", display: "flex", alignItems: "center" }}>CMYK</div>
            </div>

            {/* Color Values Columns */}
            {selectedColor.shades.map((shade: any, idx: number) => (
              <div key={idx} style={{ display: "flex", flexDirection: "column", gap: "16px", paddingTop: "8px" }}>
                <div style={{ fontSize: "15px", color: "#6B7280", height: "32px", display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center" }}>
                  {shade.hex}
                </div>
                <div style={{ fontSize: "15px", color: "#6B7280", height: "32px", display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center" }}>
                  {shade.rgb}
                </div>
                <div style={{ fontSize: "15px", color: "#6B7280", height: "32px", display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center" }}>
                  {shade.cmyk}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
