interface TypographySlideProps {
  backgroundImage: string;
  isActive: boolean;
  slideIndex: number;
  animationClass?: string;
}

/**
 * TypographySlide - Displays brand typography guidelines
 *
 * FUTURE: This data will be generated by GPT after analyzing the brand
 * GPT will recommend:
 * - Primary heading font
 * - Body text font
 * - Font weights and sizes
 * - Line heights and spacing
 * Based on brand personality and industry
 */
export default function TypographySlide({
  isActive,
  slideIndex,
  animationClass = "",
}: TypographySlideProps) {
  // Fetch GPT-generated typography from localStorage
  const getTypography = () => {
    try {
      const stored = localStorage.getItem('brandbookContent');
      if (stored) {
        const content = JSON.parse(stored);
        return content.typography;
      }
    } catch (error) {
      console.error('Error reading typography from localStorage:', error);
    }
    // Fallback to default typography
    return {
      heading: {
        family: "Inter",
        weights: ["Regular (400)", "Semi-Bold (600)", "Bold (700)"],
        usage: "Headlines, titles, and emphasis",
      },
      body: {
        family: "Inter",
        weights: ["Regular (400)", "Medium (500)"],
        usage: "Body text, descriptions, and captions",
      },
    };
  };

  const typography = getTypography();

  return (
    <div
      data-slide={slideIndex}
      className={`absolute inset-0 ${animationClass}`}
      style={{
        opacity: isActive || animationClass ? 1 : 0,
        pointerEvents: isActive ? "auto" : "none",
        zIndex: isActive ? 10 : animationClass ? 9 : 0,
        backgroundColor: "#FFFFFF",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        overflow: "auto",
      }}
    >
      {/* Main Container */}
      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "60px 80px",
          gap: "40px",
        }}
      >
        {/* Header */}
        <div style={{ flexShrink: 0 }}>
          <h1
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: "40px",
              fontWeight: 700,
              color: "#0A0A0A",
              marginBottom: "8px",
              letterSpacing: "-0.02em",
            }}
          >
            Typography
          </h1>
          <p
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: "16px",
              color: "#6B7280",
              fontWeight: 400,
            }}
          >
            Font system and typographic standards
          </p>
        </div>

        {/* Content */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "60px", flexShrink: 0 }}>
        {/* Primary Font (Headings) */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ flex: 1 }}>
            {/* Font Display */}
            <div style={{ marginBottom: "28px" }}>
              <h2
                style={{
                  fontFamily: typography.heading.family + ", sans-serif",
                  fontSize: "48px",
                  fontWeight: 700,
                  color: "#8F00FF",
                  marginBottom: "16px",
                  lineHeight: "1.1",
                  letterSpacing: "-0.02em",
                }}
              >
                Aa Bb Cc
              </h2>
              <p
                style={{
                  fontFamily: typography.heading.family + ", sans-serif",
                  fontSize: "24px",
                  fontWeight: 600,
                  color: "#1F2937",
                  lineHeight: "1.3",
                }}
              >
                The quick brown fox
              </p>
            </div>

            {/* Font Info */}
            <h3
              style={{
                fontFamily: "Inter, sans-serif",
                fontSize: "20px",
                fontWeight: 600,
                color: "#0A0A0A",
                marginBottom: "12px",
              }}
            >
              {typography.heading.family}
            </h3>
            <p
              style={{
                fontFamily: "Inter, sans-serif",
                fontSize: "14px",
                color: "#6B7280",
                marginBottom: "20px",
                lineHeight: "1.6",
              }}
            >
              {typography.heading.usage}
            </p>

            {/* Weights */}
            <div style={{ marginBottom: "24px" }}>
              <p
                style={{
                  fontFamily: "Inter, sans-serif",
                  fontSize: "13px",
                  fontWeight: 600,
                  color: "#1F2937",
                  marginBottom: "10px",
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                }}
              >
                Available Weights
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                {typography.heading.weights.map((weight, idx) => (
                  <p
                    key={idx}
                    style={{
                      fontFamily: "Inter, sans-serif",
                      fontSize: "14px",
                      color: "#6B7280",
                    }}
                  >
                    {weight}
                  </p>
                ))}
              </div>
            </div>

            {/* Size Scale */}
            <div>
              <p
                style={{
                  fontFamily: "Inter, sans-serif",
                  fontSize: "13px",
                  fontWeight: 600,
                  color: "#1F2937",
                  marginBottom: "12px",
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                }}
              >
                Size Scale
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <p
                    style={{
                      fontFamily: typography.heading.family + ", sans-serif",
                      fontSize: "28px",
                      fontWeight: 700,
                      color: "#1F2937",
                      lineHeight: "1.2",
                    }}
                  >
                    Heading 1
                  </p>
                  <p
                    style={{
                      fontFamily: "Inter, sans-serif",
                      fontSize: "11px",
                      color: "#9CA3AF",
                      marginTop: "3px",
                    }}
                  >
                    28px / Bold
                  </p>
                </div>
                <div>
                  <p
                    style={{
                      fontFamily: typography.heading.family + ", sans-serif",
                      fontSize: "22px",
                      fontWeight: 600,
                      color: "#1F2937",
                      lineHeight: "1.2",
                    }}
                  >
                    Heading 2
                  </p>
                  <p
                    style={{
                      fontFamily: "Inter, sans-serif",
                      fontSize: "11px",
                      color: "#9CA3AF",
                      marginTop: "3px",
                    }}
                  >
                    22px / Semi-Bold
                  </p>
                </div>
                <div>
                  <p
                    style={{
                      fontFamily: typography.heading.family + ", sans-serif",
                      fontSize: "18px",
                      fontWeight: 600,
                      color: "#1F2937",
                      lineHeight: "1.3",
                    }}
                  >
                    Heading 3
                  </p>
                  <p
                    style={{
                      fontFamily: "Inter, sans-serif",
                      fontSize: "11px",
                      color: "#9CA3AF",
                      marginTop: "3px",
                    }}
                  >
                    18px / Semi-Bold
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Body Font */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ flex: 1 }}>
            {/* Font Display */}
            <div style={{ marginBottom: "28px", backgroundColor: "#F9FAFB", padding: "24px", borderRadius: "8px" }}>
              <p
                style={{
                  fontFamily: typography.body.family + ", sans-serif",
                  fontSize: "16px",
                  fontWeight: 400,
                  color: "#1F2937",
                  lineHeight: "1.7",
                  marginBottom: "14px",
                }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
              <p
                style={{
                  fontFamily: typography.body.family + ", sans-serif",
                  fontSize: "14px",
                  fontWeight: 400,
                  color: "#6B7280",
                  lineHeight: "1.6",
                }}
              >
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div>

            {/* Font Info */}
            <h3
              style={{
                fontFamily: "Inter, sans-serif",
                fontSize: "20px",
                fontWeight: 600,
                color: "#0A0A0A",
                marginBottom: "12px",
              }}
            >
              {typography.body.family}
            </h3>
            <p
              style={{
                fontFamily: "Inter, sans-serif",
                fontSize: "14px",
                color: "#6B7280",
                marginBottom: "20px",
                lineHeight: "1.6",
              }}
            >
              {typography.body.usage}
            </p>

            {/* Weights */}
            <div style={{ marginBottom: "24px" }}>
              <p
                style={{
                  fontFamily: "Inter, sans-serif",
                  fontSize: "13px",
                  fontWeight: 600,
                  color: "#1F2937",
                  marginBottom: "10px",
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                }}
              >
                Available Weights
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                {typography.body.weights.map((weight, idx) => (
                  <p
                    key={idx}
                    style={{
                      fontFamily: "Inter, sans-serif",
                      fontSize: "14px",
                      color: "#6B7280",
                    }}
                  >
                    {weight}
                  </p>
                ))}
              </div>
            </div>

            {/* Size Scale */}
            <div>
              <p
                style={{
                  fontFamily: "Inter, sans-serif",
                  fontSize: "13px",
                  fontWeight: 600,
                  color: "#1F2937",
                  marginBottom: "12px",
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                }}
              >
                Size Scale
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                <div>
                  <p
                    style={{
                      fontFamily: typography.body.family + ", sans-serif",
                      fontSize: "16px",
                      fontWeight: 400,
                      color: "#1F2937",
                      lineHeight: "1.6",
                    }}
                  >
                    Body Large — 16px / Regular
                  </p>
                </div>
                <div>
                  <p
                    style={{
                      fontFamily: typography.body.family + ", sans-serif",
                      fontSize: "14px",
                      fontWeight: 400,
                      color: "#1F2937",
                      lineHeight: "1.6",
                    }}
                  >
                    Body Regular — 14px / Regular
                  </p>
                </div>
                <div>
                  <p
                    style={{
                      fontFamily: typography.body.family + ", sans-serif",
                      fontSize: "12px",
                      fontWeight: 400,
                      color: "#6B7280",
                      lineHeight: "1.5",
                    }}
                  >
                    Body Small — 12px / Regular
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  );
}
