export const industries = [
  { value: "accounting", label: "Accounting & Auditing" },
  { value: "advertising", label: "Advertising & Marketing" },
  { value: "agriculture", label: "Agriculture & Farming" },
  { value: "animation", label: "Animation & VFX" },
  { value: "architecture", label: "Architecture & Planning" },
  { value: "art-design", label: "Art & Design" },
  { value: "automotive", label: "Automotive" },
  { value: "aviation", label: "Aviation & Aerospace" },
  { value: "banking", label: "Banking & Financial Services" },
  { value: "beauty-cosmetics", label: "Beauty & Cosmetics" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "blockchain", label: "Blockchain & Cryptocurrency" },
  { value: "branding", label: "Branding & Identity" },
  { value: "broadcasting", label: "Broadcasting" },
  { value: "call-center", label: "Call Center & BPO" },
  { value: "carpentry", label: "Carpentry & Woodworking" },
  { value: "chemical", label: "Chemical Manufacturing" },
  { value: "childcare", label: "Childcare & Early Education" },
  { value: "civil-engineering", label: "Civil Engineering" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "coaching", label: "Coaching & Mentoring" },
  { value: "construction", label: "Construction" },
  { value: "consulting", label: "Consulting" },
  { value: "consumer-goods", label: "Consumer Goods" },
  { value: "content-creation", label: "Content Creation & Influencer" },
  { value: "courier", label: "Courier & Delivery Services" },
  { value: "crafts", label: "Crafts & Handmade Goods" },
  { value: "creative-agency", label: "Creative Agency" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "data-analytics", label: "Data Analytics & Business Intelligence" },
  { value: "dental", label: "Dental Services" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "ecommerce", label: "E-commerce" },
  { value: "education", label: "Education & Training" },
  { value: "electrical-engineering", label: "Electrical Engineering" },
  { value: "electronics", label: "Electronics" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "entertainment", label: "Entertainment & Media" },
  { value: "environmental", label: "Environmental Services" },
  { value: "event-planning", label: "Event Planning & Management" },
  { value: "facilities-management", label: "Facilities Management" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "film-production", label: "Film & Production" },
  { value: "financial-planning", label: "Financial Planning & Advisory" },
  { value: "fintech", label: "FinTech" },
  { value: "fitness", label: "Fitness & Wellness" },
  { value: "food-beverage", label: "Food & Beverage" },
  { value: "franchising", label: "Franchising" },
  { value: "freelancing", label: "Freelancing & Gig Economy" },
  { value: "furniture", label: "Furniture & Home Decor" },
  { value: "gaming", label: "Gaming & Esports" },
  { value: "gardening", label: "Gardening & Landscaping" },
  { value: "government", label: "Government & Public Sector" },
  { value: "graphic-design", label: "Graphic Design" },
  { value: "green-technology", label: "Green Technology" },
  { value: "hardware", label: "Hardware & IoT" },
  { value: "healthcare", label: "Healthcare & Medical" },
  { value: "higher-education", label: "Higher Education & Universities" },
  { value: "home-services", label: "Home Services & Maintenance" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "hr", label: "Human Resources" },
  { value: "hvac", label: "HVAC & Climate Control" },
  { value: "immigration", label: "Immigration Services" },
  { value: "industrial-design", label: "Industrial Design" },
  { value: "information-technology", label: "Information Technology" },
  { value: "insurance", label: "Insurance" },
  { value: "interior-design", label: "Interior Design" },
  { value: "internet", label: "Internet & Web Services" },
  { value: "investment", label: "Investment Management" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "journalism", label: "Journalism & News Media" },
  { value: "laboratory", label: "Laboratory & Testing Services" },
  { value: "legal", label: "Legal Services" },
  { value: "libraries", label: "Libraries & Archives" },
  { value: "logistics", label: "Logistics & Supply Chain" },
  { value: "luxury-goods", label: "Luxury Goods & Services" },
  { value: "machinery", label: "Machinery & Equipment" },
  { value: "management", label: "Management Consulting" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "maritime", label: "Maritime & Shipping" },
  { value: "market-research", label: "Market Research" },
  { value: "massage-therapy", label: "Massage Therapy & Spa" },
  { value: "mechanical-engineering", label: "Mechanical Engineering" },
  { value: "mental-health", label: "Mental Health & Counseling" },
  { value: "mining", label: "Mining & Metals" },
  { value: "mobile-apps", label: "Mobile App Development" },
  { value: "music", label: "Music & Audio Production" },
  { value: "nanotechnology", label: "Nanotechnology" },
  { value: "nonprofit", label: "Non-Profit Organizations" },
  { value: "nutrition", label: "Nutrition & Dietetics" },
  { value: "oil-gas", label: "Oil & Gas" },
  { value: "online-learning", label: "Online Learning & EdTech" },
  { value: "outsourcing", label: "Outsourcing & Offshoring" },
  { value: "packaging", label: "Packaging & Labeling" },
  { value: "performing-arts", label: "Performing Arts & Theater" },
  { value: "pest-control", label: "Pest Control Services" },
  { value: "pet-care", label: "Pet Care & Services" },
  { value: "pharmaceuticals", label: "Pharmaceuticals" },
  { value: "photography", label: "Photography & Videography" },
  { value: "plumbing", label: "Plumbing Services" },
  { value: "podcasting", label: "Podcasting" },
  { value: "printing", label: "Printing & Publishing" },
  { value: "procurement", label: "Procurement & Sourcing" },
  { value: "property-management", label: "Property Management" },
  { value: "public-relations", label: "Public Relations" },
  { value: "quality-assurance", label: "Quality Assurance & Testing" },
  { value: "rail-transport", label: "Rail Transport" },
  { value: "real-estate", label: "Real Estate" },
  { value: "recruitment", label: "Recruitment & Staffing" },
  { value: "renewable-energy", label: "Renewable Energy" },
  { value: "research", label: "Research & Development" },
  { value: "restaurants", label: "Restaurants & Catering" },
  { value: "retail", label: "Retail" },
  { value: "robotics", label: "Robotics & Automation" },
  { value: "saas", label: "SaaS (Software as a Service)" },
  { value: "security", label: "Security Services" },
  { value: "semiconductors", label: "Semiconductors" },
  { value: "seo", label: "SEO & SEM Services" },
  { value: "social-media", label: "Social Media Management" },
  { value: "software-development", label: "Software Development" },
  { value: "solar-energy", label: "Solar Energy" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "staffing", label: "Staffing & Temporary Labor" },
  { value: "sustainability", label: "Sustainability Consulting" },
  { value: "tax-services", label: "Tax Services" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "textile", label: "Textile & Clothing Manufacturing" },
  { value: "translation", label: "Translation & Localization" },
  { value: "transportation", label: "Transportation" },
  { value: "travel", label: "Travel & Tourism" },
  { value: "ui-ux-design", label: "UI/UX Design" },
  { value: "venture-capital", label: "Venture Capital & Private Equity" },
  { value: "veterinary", label: "Veterinary Services" },
  { value: "virtual-reality", label: "Virtual Reality & AR" },
  { value: "warehouse", label: "Warehousing & Storage" },
  { value: "waste-management", label: "Waste Management & Recycling" },
  { value: "web-development", label: "Web Development" },
  { value: "wedding-services", label: "Wedding Services" },
  { value: "wellness", label: "Wellness & Alternative Medicine" },
  { value: "wholesale", label: "Wholesale & Distribution" },
  { value: "other", label: "Other" },
];
