export const industries = [
  { value: "advertising", label: "Advertising & Marketing" },
  { value: "agriculture", label: "Agriculture & Farming" },
  { value: "architecture", label: "Architecture & Planning" },
  { value: "automotive", label: "Automotive" },
  { value: "aviation", label: "Aviation & Aerospace" },
  { value: "banking", label: "Banking & Financial Services" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "blockchain", label: "Blockchain & Cryptocurrency" },
  { value: "chemical", label: "Chemical Manufacturing" },
  { value: "civil-engineering", label: "Civil Engineering" },
  { value: "construction", label: "Construction" },
  { value: "consulting", label: "Consulting" },
  { value: "consumer-goods", label: "Consumer Goods" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "ecommerce", label: "E-commerce" },
  { value: "education", label: "Education & Training" },
  { value: "electronics", label: "Electronics" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "entertainment", label: "Entertainment & Media" },
  { value: "environmental", label: "Environmental Services" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "fintech", label: "FinTech" },
  { value: "food-beverage", label: "Food & Beverage" },
  { value: "gaming", label: "Gaming & Esports" },
  { value: "government", label: "Government & Public Sector" },
  { value: "healthcare", label: "Healthcare & Medical" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "hr", label: "Human Resources" },
  { value: "insurance", label: "Insurance" },
  { value: "interior-design", label: "Interior Design" },
  { value: "internet", label: "Internet & Web Services" },
  { value: "legal", label: "Legal Services" },
  { value: "logistics", label: "Logistics & Supply Chain" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "maritime", label: "Maritime & Shipping" },
  { value: "mining", label: "Mining & Metals" },
  { value: "nonprofit", label: "Non-Profit Organizations" },
  { value: "oil-gas", label: "Oil & Gas" },
  { value: "pharmaceuticals", label: "Pharmaceuticals" },
  { value: "photography", label: "Photography & Videography" },
  { value: "printing", label: "Printing & Publishing" },
  { value: "real-estate", label: "Real Estate" },
  { value: "renewable-energy", label: "Renewable Energy" },
  { value: "research", label: "Research & Development" },
  { value: "restaurants", label: "Restaurants & Catering" },
  { value: "retail", label: "Retail" },
  { value: "saas", label: "SaaS (Software as a Service)" },
  { value: "security", label: "Security Services" },
  { value: "semiconductors", label: "Semiconductors" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "textile", label: "Textile & Clothing Manufacturing" },
  { value: "transportation", label: "Transportation" },
  { value: "travel", label: "Travel & Tourism" },
  { value: "venture-capital", label: "Venture Capital & Private Equity" },
  { value: "veterinary", label: "Veterinary Services" },
  { value: "warehouse", label: "Warehousing & Storage" },
  { value: "waste-management", label: "Waste Management & Recycling" },
  { value: "wholesale", label: "Wholesale & Distribution" },
  { value: "other", label: "Other" },
];
