import { useState, useEffect, useRef } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useNavigate } from "react-router-dom";
import CenteredLogoSlide from "./slides/CenteredLogoSlide";
import TwoTshirtSlide from "./slides/TwoTshirtSlide";
import RightLogoSlide from "./slides/RightLogoSlide";
import FourColorVariantsSlide from "./slides/FourColorVariantsSlide";
import ColorPaletteSlide from "./slides/ColorPaletteSlide";
import TypographySlide from "./slides/TypographySlide";
import BrandVoiceSlide from "./slides/BrandVoiceSlide";
import VisualStyleSlide from "./slides/VisualStyleSlide";
import UsageExamplesSlide from "./slides/UsageExamplesSlide";
import bg1 from "@/assets/brandbook/1.png";
import bg2 from "@/assets/brandbook/2.png";
import bg3 from "@/assets/brandbook/3.png";
import bg4 from "@/assets/brandbook/4.png";
import bg5 from "@/assets/brandbook/5.png";
import bg6 from "@/assets/brandbook/6.png";
import "./BrandbookSlider.css";

interface BrandbookSliderProps {
  isOpen: boolean;
  onClose: () => void;
  logoVariants?: {
    blackBg: string;
    whiteBg: string;
    lightRedBg: string;
    yellowBg: string;
  } | null;
}

interface SlideConfig {
  id: number;
  bgImage: string;
  title: string;
  type: "centered" | "two-tshirt" | "right-logo" | "four-color-variants" | "color-palette" | "typography" | "brand-voice" | "visual-style" | "usage-examples";
  backgroundSize?: "cover" | "contain" | "100% 100%";
  logoTopPosition?: string;
  logoLeftPosition?: string;
  logoSize?: string;
}

export default function BrandbookSlider({
  isOpen,
  onClose,
  logoVariants,
}: BrandbookSliderProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [previousSlide, setPreviousSlide] = useState(0);
  const [isAnimating, setIsAnimating] = useState(false);
  const [direction, setDirection] = useState<"next" | "prev">("next");
  const [showDownloadDialog, setShowDownloadDialog] = useState(false);
  const [isExportingPDF, setIsExportingPDF] = useState(false);
  const [isExportingPPTX, setIsExportingPPTX] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();

  /**
   * Brandbook Slide Configuration
   *
   * FUTURE: All content-based slides (color-palette, typography, brand-voice,
   * visual-style, usage-examples) will have their data generated by GPT after
   * analyzing the brand logo and onboarding responses.
   *
   * GPT will analyze:
   * - Logo colors, style, and composition
   * - Brand personality from onboarding
   * - Industry standards and best practices
   * - Target audience preferences
   *
   * Then generate comprehensive brandbook content dynamically.
   */
  const slides: SlideConfig[] = [
    { id: 1, bgImage: bg1, title: "Brand Book - Cover", type: "centered", logoSize: "400px", logoTopPosition: "50%" },
    { id: 2, bgImage: bg2, title: "Brand Book - Logo Showcase", type: "centered", logoSize: "400px", logoTopPosition: "50%" },
    { id: 4, bgImage: bg4, title: "Logo Variants", type: "four-color-variants" },
    { id: 3, bgImage: bg3, title: "Brand Book - Products", type: "two-tshirt" },
    // NEW: Four Color Variants Slide (at position 4)
    // { id: 4, bgImage: bg4, title: "Logo Variants", type: "four-color-variants" },
    { id: 5, bgImage: bg4, title: "Brand Book - Application", type: "centered", logoSize: "360px", logoTopPosition: "55%", logoLeftPosition: "49%" },
    { id: 6, bgImage: bg5, title: "Brand Book - Context", type: "centered", backgroundSize: "100% 100%", logoTopPosition: "45%", logoSize: "350px", logoLeftPosition: "50%" },
    { id: 7, bgImage: bg6, title: "Brand Book - Display", type: "right-logo", logoSize: "400px" },
    // GPT-Generated Content Slides (Currently hardcoded, will be dynamic)
    { id: 8, bgImage: bg1, title: "Primary Color", type: "color-palette" },
    { id: 9, bgImage: bg2, title: "Secondary Color", type: "color-palette" },
    { id: 10, bgImage: bg3, title: "Typography Guidelines", type: "typography" },
    { id: 11, bgImage: bg4, title: "Brand Voice & Tone", type: "brand-voice" },
    { id: 12, bgImage: bg5, title: "Visual Style Guide", type: "visual-style" },
    { id: 13, bgImage: bg6, title: "Usage Examples", type: "usage-examples" },
  ];

  // Lock body scroll when slider is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [isOpen]);

  // Keyboard navigation
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") handleNext();
      if (e.key === "ArrowLeft") handlePrev();
      if (e.key === "Escape") onClose();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, currentSlide, isAnimating]);

  const handleNext = () => {
    if (currentSlide < slides.length - 1 && !isAnimating) {
      setDirection("next");
      setIsAnimating(true);
      setPreviousSlide(currentSlide);
      setCurrentSlide(currentSlide + 1);
      setTimeout(() => {
        setIsAnimating(false);
      }, 600); // Match animation duration
    }
  };

  const handlePrev = () => {
    if (currentSlide === 0 && !isAnimating) {
      // On first slide, go back to logo page
      onClose();
      navigate("/onboarding/logo-generation");
    } else if (currentSlide > 0 && !isAnimating) {
      setDirection("prev");
      setIsAnimating(true);
      setPreviousSlide(currentSlide);
      setCurrentSlide(currentSlide - 1);
      setTimeout(() => {
        setIsAnimating(false);
      }, 600); // Match animation duration
    }
  };

  const handleCloseSlider = () => {
    // Show download dialog when closing slider
    setShowDownloadDialog(true);
  };

  const handleSkipDownload = () => {
    setShowDownloadDialog(false);
    onClose();
    // Navigate to step 2 (business content setup)
    navigate("/onboarding/business-content-setup");
  };

  const handleDownload = async (format: "pptx" | "pdf") => {
    try {
      if (format === "pdf") {
        setIsExportingPDF(true);
        await exportAsPDF();
      } else {
        setIsExportingPPTX(true);
        await exportAsPPTX();
      }

      // After successful download, close dialog and navigate
      setTimeout(() => {
        setShowDownloadDialog(false);
        onClose();
        navigate("/onboarding/business-content-setup");
      }, 1000);
    } catch (error) {
      console.error("Export failed:", error);
      if (format === "pdf") {
        setIsExportingPDF(false);
      } else {
        setIsExportingPPTX(false);
      }
    }
  };

  const exportAsPDF = async () => {
    const { toPng } = await import("html-to-image");
    const { jsPDF } = await import("jspdf");

    const slideElements = Array.from(
      containerRef.current?.querySelectorAll('[data-slide]') || []
    );

    if (slideElements.length === 0) {
      console.error("No slides found for export");
      setIsExportingPDF(false);
      return;
    }

    const pdf = new jsPDF({
      orientation: "landscape",
      unit: "px",
      format: [1920, 1080],
    });

    // Store original styles
    const originalStyles = slideElements.map(el => ({
      element: el as HTMLElement,
      opacity: (el as HTMLElement).style.opacity,
      zIndex: (el as HTMLElement).style.zIndex,
      pointerEvents: (el as HTMLElement).style.pointerEvents,
      position: (el as HTMLElement).style.position,
      width: (el as HTMLElement).style.width,
      height: (el as HTMLElement).style.height,
      inset: (el as HTMLElement).style.inset,
    }));

    // Make all slides visible and set explicit dimensions
    slideElements.forEach(slideEl => {
      const element = slideEl as HTMLElement;
      element.style.opacity = "1";
      element.style.zIndex = "10";
      element.style.pointerEvents = "auto";
      element.style.position = "absolute";
      element.style.width = "1920px";
      element.style.height = "1080px";
      element.style.inset = "0";
    });

    // Wait for styles to apply
    await new Promise(resolve => setTimeout(resolve, 200));

    for (let i = 0; i < slideElements.length; i++) {
      const imgData = await toPng(slideElements[i] as HTMLElement, {
        quality: 1,
        pixelRatio: 1, // Changed from 2 to 1 to maintain logo sizes and alignment
        width: 1920,
        height: 1080,
        cacheBust: true,
      });

      if (i > 0) pdf.addPage();
      pdf.addImage(imgData, "PNG", 0, 0, 1920, 1080);
    }

    // Restore original styles
    originalStyles.forEach(({ element, opacity, zIndex, pointerEvents, position, width, height, inset }) => {
      element.style.opacity = opacity;
      element.style.zIndex = zIndex;
      element.style.pointerEvents = pointerEvents;
      element.style.position = position;
      element.style.width = width;
      element.style.height = height;
      element.style.inset = inset;
    });

    pdf.save("Brandbook.pdf");
    setIsExportingPDF(false);
  };

  const exportAsPPTX = async () => {
    try {
      const { toPng } = await import("html-to-image");
      const pptxgenModule = await import("pptxgenjs");
      const PptxGenJS = pptxgenModule.default || pptxgenModule;

      const slideElements = Array.from(
        containerRef.current?.querySelectorAll('[data-slide]') || []
      );

      if (slideElements.length === 0) {
        console.error("No slides found for export");
        setIsExportingPPTX(false);
        return;
      }

      // Store original styles
      const originalStyles = slideElements.map(el => ({
        element: el as HTMLElement,
        opacity: (el as HTMLElement).style.opacity,
        zIndex: (el as HTMLElement).style.zIndex,
        pointerEvents: (el as HTMLElement).style.pointerEvents,
        position: (el as HTMLElement).style.position,
        width: (el as HTMLElement).style.width,
        height: (el as HTMLElement).style.height,
        inset: (el as HTMLElement).style.inset,
      }));

      // Make all slides visible and set explicit dimensions
      slideElements.forEach(slideEl => {
        const element = slideEl as HTMLElement;
        element.style.opacity = "1";
        element.style.zIndex = "10";
        element.style.pointerEvents = "auto";
        element.style.position = "absolute";
        element.style.width = "1920px";
        element.style.height = "1080px";
        element.style.inset = "0";
      });

      // Wait for styles to apply
      await new Promise(resolve => setTimeout(resolve, 200));

      const pptx = new PptxGenJS();
      pptx.layout = "LAYOUT_16x9";
      pptx.author = "Marqait Brand Guidelines";
      pptx.title = "Brandbook";

      for (let i = 0; i < slideElements.length; i++) {
        const imgData = await toPng(slideElements[i] as HTMLElement, {
          quality: 1,
          pixelRatio: 1, // Changed from 2 to 1 to maintain logo sizes and alignment
          width: 1920,
          height: 1080,
          cacheBust: true,
        });

        const slide = pptx.addSlide();
        slide.background = { data: imgData };
      }

      // Restore original styles
      originalStyles.forEach(({ element, opacity, zIndex, pointerEvents, position, width, height, inset }) => {
        element.style.opacity = opacity;
        element.style.zIndex = zIndex;
        element.style.pointerEvents = pointerEvents;
        element.style.position = position;
        element.style.width = width;
        element.style.height = height;
        element.style.inset = inset;
      });

      await pptx.writeFile({ fileName: "Brandbook.pptx" });
      setIsExportingPPTX(false);
    } catch (error) {
      console.error("PPTX export failed:", error);
      setIsExportingPPTX(false);
    }
  };


  if (!isOpen) return null;

  return (
    <>
      {/* Fullscreen Overlay */}
      <div
        className="fixed inset-0 z-50 animate-slider-open"
        style={{ backgroundColor: "#000000" }}
      >

        {/* Slides Container */}
        <div
          ref={containerRef}
          className="relative w-full h-full overflow-hidden"
        >
          {slides.map((slide, index) => {
            const isActive = index === currentSlide;
            const isPrevious = index === previousSlide;

            // Determine animation class
            let animationClass = "";
            if (isAnimating) {
              if (isActive) {
                // Incoming slide
                animationClass = direction === "next"
                  ? "animate-slide-fade-in-right"
                  : "animate-slide-fade-in-left";
              } else if (isPrevious) {
                // Outgoing slide
                animationClass = direction === "next"
                  ? "animate-slide-fade-out-left"
                  : "animate-slide-fade-out-right";
              }
            }

            // Render different slide types
            if (slide.type === "two-tshirt") {
              return (
                <TwoTshirtSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  isAnimating={isAnimating}
                  direction={direction}
                  slideIndex={index}
                  animationClass={animationClass}
                />
              );
            }

            if (slide.type === "right-logo") {
              return (
                <RightLogoSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  backgroundSize={slide.backgroundSize}
                  animationClass={animationClass}
                />
              );
            }

            // NEW: Four Color Variants Slide
            if (slide.type === "four-color-variants") {
              return (
                <FourColorVariantsSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  animationClass={animationClass}
                  logoVariants={logoVariants || {
                    blackBg: '',
                    whiteBg: '',
                    lightRedBg: '',
                    yellowBg: '',
                  }}
                />
              );
            }

            // GPT-Generated Content Slides
            if (slide.type === "color-palette") {
              return (
                <ColorPaletteSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  animationClass={animationClass}
                  colorType={slide.id === 8 ? "primary" : "secondary"}
                />
              );
            }

            if (slide.type === "typography") {
              return (
                <TypographySlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  animationClass={animationClass}
                />
              );
            }

            if (slide.type === "brand-voice") {
              return (
                <BrandVoiceSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  animationClass={animationClass}
                />
              );
            }

            if (slide.type === "visual-style") {
              return (
                <VisualStyleSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  animationClass={animationClass}
                />
              );
            }

            if (slide.type === "usage-examples") {
              return (
                <UsageExamplesSlide
                  key={slide.id}
                  backgroundImage={slide.bgImage}
                  isActive={isActive}
                  slideIndex={index}
                  animationClass={animationClass}
                />
              );
            }

            // Default: Centered Logo Slide
            return (
              <CenteredLogoSlide
                key={slide.id}
                backgroundImage={slide.bgImage}
                isActive={isActive}
                slideIndex={index}
                backgroundSize={slide.backgroundSize}
                logoTopPosition={slide.logoTopPosition}
                logoLeftPosition={slide.logoLeftPosition}
                logoSize={slide.logoSize}
                animationClass={animationClass}
              />
            );
          })}
        </div>

        {/* Navigation Arrows */}
        {/* Left Arrow - Always visible, goes back to logo page on first slide */}
        <button
          onClick={handlePrev}
          disabled={isAnimating}
          className="absolute left-8 top-1/2 transition-all hover:scale-110 disabled:opacity-50 disabled:cursor-not-allowed"
          style={{
            transform: "translateY(-50%)",
            width: "56px",
            height: "56px",
            borderRadius: "50%",
            backgroundColor: "transparent",
            border: "2px solid #000000",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "pointer",
            zIndex: 30,
          }}
          aria-label={currentSlide === 0 ? "Back to logos" : "Previous slide"}
        >
          <ChevronLeft
            style={{ width: "32px", height: "32px", color: "#000000" }}
          />
        </button>

        {/* Right Arrow - Next slide or Open Dialog on last slide */}
        <button
          onClick={currentSlide < slides.length - 1 ? handleNext : handleCloseSlider}
          disabled={isAnimating}
          className="absolute right-8 top-1/2 transition-all hover:scale-110 disabled:opacity-50 disabled:cursor-not-allowed"
          style={{
            transform: "translateY(-50%)",
            width: "56px",
            height: "56px",
            borderRadius: "50%",
            backgroundColor: "transparent",
            border: "2px solid #000000",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "pointer",
            zIndex: 30,
          }}
          aria-label={currentSlide < slides.length - 1 ? "Next slide" : "Finish"}
        >
          <ChevronRight
            style={{ width: "32px", height: "32px", color: "#000000" }}
          />
        </button>

      </div>

      {/* Download Dialog */}
      {showDownloadDialog && (
        <div
          className="fixed inset-0 z-60 flex items-center justify-center"
          style={{
            backgroundColor: "rgba(0, 0, 0, 0.8)",
            backdropFilter: "blur(10px)",
          }}
          onClick={() => setShowDownloadDialog(false)}
        >
          <div
            className="relative"
            style={{
              width: "90%",
              maxWidth: "420px",
              backgroundColor: "#FFFFFF",
              borderRadius: "24px",
              padding: "24px",
              boxShadow: "0px 20px 60px rgba(0, 0, 0, 0.3)",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Dialog Header */}
            <div style={{ textAlign: "center", marginBottom: "20px" }}>
              <h2
                style={{
                  fontFamily: "Inter, sans-serif",
                  fontSize: "18px",
                  fontWeight: 600,
                  color: "#0A0A0A",
                  marginBottom: "6px",
                }}
              >
                Download Brandbook
              </h2>
              <p
                style={{
                  fontFamily: "Inter, sans-serif",
                  fontSize: "13px",
                  color: "#6B7280",
                  lineHeight: "1.4",
                }}
              >
                Choose your preferred format
              </p>
            </div>

            {/* Download Buttons in Row */}
            <div style={{ display: "flex", gap: "12px", marginBottom: "14px" }}>
              {/* PDF Button */}
              <button
                onClick={() => handleDownload("pdf")}
                disabled={isExportingPDF || isExportingPPTX}
                className="transition-all hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
                style={{
                  flex: 1,
                  padding: "10px 20px",
                  borderRadius: "12px",
                  border: "none",
                  background:
                    "radial-gradient(43.57% 80% at 49.09% 100%, #DAABFF 0%, #8F00FF 100%)",
                  fontFamily: "Inter, sans-serif",
                  fontSize: "14px",
                  fontWeight: 600,
                  color: "#FFFFFF",
                  cursor: "pointer",
                  boxShadow: "0px 4px 12px rgba(143, 0, 255, 0.25)",
                }}
              >
                {isExportingPDF ? "Loading..." : "PDF"}
              </button>

              {/* PPTX Button */}
              <button
                onClick={() => handleDownload("pptx")}
                disabled={isExportingPDF || isExportingPPTX}
                className="transition-all hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
                style={{
                  flex: 1,
                  padding: "10px 20px",
                  borderRadius: "12px",
                  border: "none",
                  background:
                    "radial-gradient(43.57% 80% at 49.09% 100%, #DAABFF 0%, #8F00FF 100%)",
                  fontFamily: "Inter, sans-serif",
                  fontSize: "14px",
                  fontWeight: 600,
                  color: "#FFFFFF",
                  cursor: "pointer",
                  boxShadow: "0px 4px 12px rgba(143, 0, 255, 0.25)",
                }}
              >
                {isExportingPPTX ? "Loading..." : "PPTX"}
              </button>
            </div>

            {/* Skip Button - Right Aligned */}
            <div style={{ display: "flex", justifyContent: "flex-end" }}>
              <button
                onClick={handleSkipDownload}
                disabled={isExportingPDF || isExportingPPTX}
                className="transition-all hover:opacity-80 disabled:opacity-50"
                style={{
                  padding: "8px 20px",
                  borderRadius: "9999px",
                  border: "1px solid #E4E4E4",
                  backgroundColor: "#FFFFFF",
                  fontFamily: "Inter, sans-serif",
                  fontSize: "13px",
                  fontWeight: 600,
                  color: "#6B7280",
                  cursor: "pointer",
                  width: "auto",
                }}
              >
                Skip
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
